### ISSUE TITLE
Reset Password screen Implementation.

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#1]

**Comment by adugamayuba** [comment]
Implement Reset password screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=1968%3A15773

![Uploading RESET PASSWORD.png…]()

**Comment by jaypee-0** [comment]
Like to work on this too slack - @Jaypee
