### ISSUE TITLE
Find Talent / candidate list Screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#10]
Implement the Find talent/candidate list screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3523%3A48907

![candidate listing](https://user-images.githubusercontent.com/31111116/191488885-2dad2168-478a-4658-96e8-bc56c992d942.png)

**Comment by worldsalt3** [comment]
I'd like to take this up
