### ISSUE TITLE
Employer listing screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#11]
Implement Employer listing screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3523%3A49833

![Employer's listing](https://user-images.githubusercontent.com/31111116/191492083-59a08fbf-c77f-463b-8b6a-ebadf02321ee.png)

**Comment by Tolulope-xo** [comment]
I'll like to fix this issue

**Comment by sammy-code98** [comment]
taken

**Comment by sammy-code98** [comment]
@adugamayuba  i have fixed this issue
