### ISSUE TITLE
make hire-talent page responsive

### ISSUE THREAD

**Issue by copy-ninja1** [AfriSplash-Remotely/Afrisplash-Frontend#119]

**Comment by Vinyl-Davyl** [comment]
any means necessary to contribute and join the team?? @copy-ninja1 
Interested in AfriSplash Product

**Comment by copy-ninja1** [comment]
ok good, @Vinyl-Davyl  email me your whats number emmajnr1000@gmail.com

**Comment by Vinyl-Davyl** [comment]
Okay

**Comment by Vinyl-Davyl** [comment]
sent! @copy-ninja1
