### ISSUE TITLE
Job listing Screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#12]
Implement Landing page/Job listing Screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3523%3A50386

![Logged in](https://user-images.githubusercontent.com/31111116/191493273-880d3f22-4ff1-4ef3-b79e-7ab9302bb160.png)

**Comment by pauxiel** [comment]
I will take this up too @pauxiel slack

**Comment by adugamayuba** [comment]
okay awesome
