### ISSUE TITLE
Fix: favicon

### ISSUE THREAD

**Issue by copy-ninja1** [AfriSplash-Remotely/Afrisplash-Frontend#123]
use this icon as the favicon.
![afrisplash_main_logo 2](https://user-images.githubusercontent.com/68874364/231309721-dfc6253c-a125-4060-a05a-606f85e1f656.png)

this are the list of favicon sizes expected
favicon-128x128
favicon-96x96
favicon-32x32
favicon-16x16

**Comment by Vinyl-Davyl** [comment]
completed

**Comment by copy-ninja1** [comment]
done
