### ISSUE TITLE
Candidate Onboarding Screens Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#13]
Implement the complete profile screens.

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=1968%3A15773

![Complete Profile](https://user-images.githubusercontent.com/31111116/191495474-ef56c9f9-8bb8-4f6c-876c-e2fde7526d4c.png)
![Education](https://user-images.githubusercontent.com/31111116/191495517-7234b81b-361f-47ad-b631-6244ac8ad2e0.png)
![Experience](https://user-images.githubusercontent.com/31111116/191495525-642936cc-b351-4039-ac58-8464c9d0900f.png)
![PROFILE PICTURE UPLOADED](https://user-images.githubusercontent.com/31111116/191495530-39034ffc-23d0-4bb7-9bdd-01017c005a2e.png)
![Skills](https://user-images.githubusercontent.com/31111116/191495533-22d3e155-8c47-4637-8759-f90969e37090.png)

**Comment by kasboi** [comment]
Would like to take this up

**Comment by CodigoGod** [comment]
Alright @kasboi, It will be assigned to you on trello as well
