### ISSUE TITLE
Hire Talent (New page)

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#131]
Implement Hire Talent Page - https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?type=design&node-id=9965%3A89458&t=tRoUHpfgrTTP3SKU-1
![Hire Talent](https://github.com/AfriSplash-Remotely/Afrisplash-Frontend/assets/96685215/5ad754a0-925d-4698-94fa-27c7ab522571)

**Comment by CodigoGod** [comment]
Taken by Alberta

**Comment by Nancy4321** [comment]
Received. I'll work on it and keep you updated

**Comment by Nancy4321** [comment]
@CodigoGod @copy-ninja1 I've created a pull request on this
