### ISSUE TITLE
About Us Page Implementation

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#133]
https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?type=design&node-id=10635%3A90144&t=dYu6S3jSmlcEu8DP-1

![ABOUT US](https://github.com/AfriSplash-Remotely/Afrisplash-Frontend/assets/96685215/40ade5b5-fe7e-4972-88d6-e41492508a2a)

**Comment by CodigoGod** [comment]
@Nancy4321 You can take up this call.

**Comment by Nancy4321** [comment]
Well received.

**Comment by copy-ninja1** [comment]
done
