### ISSUE TITLE
Terms of Use, Privacy Policy and Copyright Policy Page Implementation

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#135]
https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?type=design&node-id=10909%3A89400&t=bDEYZt3gUfT3cjUR-1
![Terms of Use](https://github.com/AfriSplash-Remotely/Afrisplash-Frontend/assets/96685215/efc75db0-b4a6-4db8-bf82-eb4b9eb8ecb9)
![Privacy Policy](https://github.com/AfriSplash-Remotely/Afrisplash-Frontend/assets/96685215/c1db1687-2159-4a80-a877-7b305cbf631d)
![Copyright Policy](https://github.com/AfriSplash-Remotely/Afrisplash-Frontend/assets/96685215/efc9c6a2-dd1a-48ef-ab24-c376b90a4a4d)

**Comment by copy-ninja1** [comment]
@sammy-code98 use markdown
