### ISSUE TITLE
Contact Us Pop Up on Hire Talent Page Implementation

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#136]
https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?type=design&node-id=11084%3A89651&t=bDEYZt3gUfT3cjUR-1
![Contact Us](https://github.com/AfriSplash-Remotely/Afrisplash-Frontend/assets/96685215/8bd789c9-5706-4407-b045-7ce742d7ac7c)

**Comment by Ilesanmi-Erioluwa-Victor** [comment]
Boss, if nobody is assign to this, kindly assign this task to me to work.

**Comment by olafisoyevince** [comment]
Good morning. I'd like to work on this feature. @CodigoGod

**Comment by sammy-code98** [comment]
@olafisoyevince  you can work on this feature .

if you need any clarity about the flow or anything pertaining to making contributions, you can reach out to @CodigoGod or me.
we are always available to help.

Looking forward to your PR

**Comment by olafisoyevince** [comment]
@sammy-code98 I am unable to push my code to my branch. GitHub said I don't have permission to do so. Can you please add me to the project so we can move on?

**Comment by sammy-code98** [comment]
Hello @olafisoyevince , sorry about that,

If you originally forked this repo to make contributions to it, you can make commits and push to your own version(repo) then create a PR(pull request) from there.

**Comment by olafisoyevince** [comment]
I have done the necessary things and I have made a PR from there. @sammy-code98 Please review

**Comment by sammy-code98** [comment]
> I have done the necessary things and I have made a PR from there. @sammy-code98 Please review

Thank you  @olafisoyevince  for making your first PR here.

Would make a review asap
Great work man

**Comment by olafisoyevince** [comment]
Thank you. Looking forward to contributing more.
