### ISSUE TITLE
Candidate / Account Set Up Screen Implementation 

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#14]
Implement candidate / Account Set up screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3512%3A45493

![Set Up Account](https://user-images.githubusercontent.com/31111116/191497299-6bb9356a-47da-4b9c-b679-c85005e6e40b.png)

**Comment by mahilday** [comment]
This has been worked on, just some changes to be done by @copy-ninja1
