### ISSUE TITLE
Notification popup

### ISSUE THREAD

**Issue by copy-ninja1** [AfriSplash-Remotely/Afrisplash-Frontend#143]
![Screenshot from 2023-06-23 13-33-41](https://github.com/AfriSplash-Remotely/Afrisplash-Frontend/assets/68874364/ec028c66-7066-483c-9d10-6600f0b488b5)

**Comment by copy-ninja1** [comment]
@Alberta-Carsamer

**Comment by Ilesanmi-Erioluwa-Victor** [comment]
Boss  @copy-ninja1 , please, assign a task to me..

**Comment by copy-ninja1** [comment]
@Ilesanmi-Erioluwa-Victor  we need to fix up your current PR #137 first

**Comment by Nancy4321** [comment]
Well noted. I work on it

**Comment by sammy-code98** [comment]
https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?type=design&node-id=3548-67065&mode=design&t=th5VXPIZihdn7nct-0
