### ISSUE TITLE
Recruiter Onboarding Screens Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#15]
Implement Recruiter Onboarding Screens 

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=1968%3A15773

![Recruiter Complete Profile](https://user-images.githubusercontent.com/31111116/191499296-1d06f47c-53a9-4b39-a18c-cc7374fed286.png)

![with menu-1](https://user-images.githubusercontent.com/31111116/191499392-bfb88f9f-d4d2-49d0-bd25-6081f1d58c0f.png)
![with menu-2](https://user-images.githubusercontent.com/31111116/191499405-b77820d0-6d1e-4087-8c09-42f66ddfd4b6.png)
![with menu](https://user-images.githubusercontent.com/31111116/191499418-a3402ace-ef7e-4be1-a8ca-a39758cb5288.png)
![without menu](https://user-images.githubusercontent.com/31111116/191499438-8b0e81b7-8c1f-4373-af21-71dfe7ff1f8c.png)
![Sign up-1](https://user-images.githubusercontent.com/31111116/191499487-1556a0f8-e60e-4d9f-9434-8a835d49e368.png)
![Sign up](https://user-images.githubusercontent.com/31111116/191499499-8aa6f440-57f1-43eb-a0a9-d45d05eaa3ab.png)

**Comment by shagariboy** [comment]
I will work on this.

**Comment by mahilday** [comment]
I just picked this
