### ISSUE TITLE
Candidate profile view screens implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#17]
Implement the candidate profile view screens.

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=1968%3A15773

![Candidate View (My profile)](https://user-images.githubusercontent.com/31111116/191504404-473ac4d2-997b-4f34-8921-41ffd03e40be.png)
![Employer View, Candidate Profile](https://user-images.githubusercontent.com/31111116/191504413-ba7dec56-f923-4c1b-a925-c1a67d04ff35.png)

**Comment by Sochima-Aristotle** [comment]
Hi guys I would like like to work on this part of the project.

**Comment by adugamayuba** [comment]
Hi man, sure keep me updated on the progress.

**Comment by adugamayuba** [comment]
Hi man, sure keep me updated on the progress.

**Comment by Sochima-Aristotle** [comment]
Ok boss.

**Comment by mahilday** [comment]
This task has not been worked on yet so I'll be taking this up now to speed up the process
