### ISSUE TITLE
Candidate Jobs - Saved & Applied screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#18]
Implement the Candidate Jobs - Saved & Applied screens 

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=1968%3A15773

![APPLIED JOBS](https://user-images.githubusercontent.com/31111116/191507620-1d68ca9f-4ac9-4665-8b54-e13103a78f4a.png)
![JOBS](https://user-images.githubusercontent.com/31111116/191507646-a5cebe18-e586-4a4b-8b0d-547b3ae7d6a1.png)
![SAVED JOBS](https://user-images.githubusercontent.com/31111116/191507659-49eb7142-9a45-4ce1-be37-0a667b97f5b2.png)

**Comment by chysomm62** [comment]
Hi, I’m interested in working on this issue.
