### ISSUE TITLE
Message Screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#19]
Implement message screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3523%3A52215

![Messages](https://user-images.githubusercontent.com/31111116/191509113-cd5084a3-12db-4d09-8891-6f6813cf3776.png)

**Comment by pauxiel** [comment]
I will take this up @pauxiel slack
