### ISSUE TITLE
Login Screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#2]
Implement the Login screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=1968%3A15773

![Login Page](https://user-images.githubusercontent.com/31111116/188276045-0ba34669-3451-481a-aa99-92dff408c70a.png)

**Comment by jaypee-0** [comment]
Jaypee would love to work on this issue

**Comment by adugamayuba** [comment]
Hi Jaypee,
okay sure, keep updated on the progress, plus if you have any issues don't hesitate to reach out to me for clarity.

**Comment by adugamayuba** [comment]
Hi @jaypee-0 how's it going?

Whats the status of this current implementation?

**Comment by CodigoGod** [comment]
@jaypee-0 check the design in your available time for an updated structure as some changes were made for alignment.

Thanks

**Comment by CodigoGod** [comment]
@jaypee-0 Two new screens were added in the login flow for google SSO

**Comment by jaypee-0** [comment]
noted, will fix them up tonight
