### ISSUE TITLE
Forum Home Screen Implementation

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#22]
Implement Forum Home Screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3548%3A66233

![Home View](https://user-images.githubusercontent.com/96685215/191732621-869d41da-71eb-4594-b106-65c01a268b09.png)

**Comment by iamenochlee** [comment]
Taken, will work on this
