### ISSUE TITLE
Mentor Listing Screen Implementation

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#28]
https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3548%3A66123

![Home View (MENTORS HUB)](https://user-images.githubusercontent.com/96685215/192559908-cddb8522-6cbe-47d6-9d80-d62f6d46ea18.png)

**Comment by sammy-code98** [comment]
taken

**Comment by sammy-code98** [comment]
@CodigoGod  this issue has been fixed
