### ISSUE TITLE
Recruiter Profile - Candidate View  and My View Screen Implementation

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#29]
Implement Recruiter Profile - Candidate View Screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3548%3A60900

![Candidate view](https://user-images.githubusercontent.com/96685215/192569062-5a208ba9-c555-474f-8be9-ea781c1f82c4.png)
![tooltip](https://user-images.githubusercontent.com/96685215/192569218-a0eaba56-9f04-4a9f-a2c2-95661b8584b7.png)
![with tootltip for info](https://user-images.githubusercontent.com/96685215/192569249-d4b57f18-3a54-47c8-90cf-58d46e0028e1.png)

**Comment by Ilesanmi-Erioluwa-Victor** [comment]
I will be going for this display...
