### ISSUE TITLE
Sign up screen implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#3]
Implement the signup screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=1968%3A15773

![SIGN UP PAGE](https://user-images.githubusercontent.com/31111116/188276324-ffdf9ab5-2856-40b8-8ec1-bb4997f45955.png)

**Comment by jaypee-0** [comment]
I'll take this up too  slack - @Jaypee

**Comment by CodigoGod** [comment]
@jaypee-0 New design update for this screen on Figma

Please review and incorporate. Thanks

**Comment by jaypee-0** [comment]
noted

**Comment by mahilday** [comment]
No feedback has been gotten yet so I am assigning @Paige-cyber25
