### ISSUE TITLE
Company Profile View Screen Implementation

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#31]
Implement Company Profile View Screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3548%3A61276

![Company Profile](https://user-images.githubusercontent.com/96685215/192573637-df94b73d-deee-4769-93e5-028c09f47724.png)

**Comment by kenedilichi1** [comment]
taken

**Comment by kenedilichi1** [comment]
i'm done with this
