### ISSUE TITLE
Post Jobs <SignIn user> Screens Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#34]
Implement Post jobs screens for signed-in users.

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=1968%3A15773

![Confirmation](https://user-images.githubusercontent.com/31111116/192759441-6e073b27-31a4-4603-ae9b-d64b13e3ff98.png)
![Package plan](https://user-images.githubusercontent.com/31111116/192759456-dfd416b6-4db9-4e64-88fe-da294e666878.png)
![Post a new Job 16](https://user-images.githubusercontent.com/31111116/192759460-1720fa4d-e6d2-4d30-a866-60aaebc2c1f3.png)
![Post a new Job 17](https://user-images.githubusercontent.com/31111116/192759465-f7ffaf18-87db-44b2-af60-ea1b9a2883d3.png)
![Post a new job](https://user-images.githubusercontent.com/31111116/192759467-81d8e97e-e110-49cf-9672-1e0358a9dabf.png)

**Comment by KenjxJJ** [comment]
Commented for work!

**Comment by shagariboy** [comment]
i will work on this.

**Comment by Sochima-Aristotle** [comment]
@shagariboy do you mind if I join you in this issue? because I noticed it's a bit much and also to speed up the rate of the design.

**Comment by shagariboy** [comment]
@Sochima-Aristotle  Sure

**Comment by Sochima-Aristotle** [comment]
Let us link up on whatsapp so that I can know how to come in, if you don't mind.
