### ISSUE TITLE
Recruiters Job page screen implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#35]
Implement the recruiter Job page screen 

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3524%3A48068

![RECRUITER'S JOB PAGE](https://user-images.githubusercontent.com/31111116/192759918-49ce8bf7-d0d9-4524-b42e-e35a750e7db1.png)

**Comment by copy-ninja1** [comment]
am working on this
