### ISSUE TITLE
Manage Job Post Screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#36]
Implement Job Post screen 

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3524%3A48235

![MANAGE JOB POSTS](https://user-images.githubusercontent.com/31111116/192760298-b1190def-9e32-43ee-b2bd-b8efa7106cfd.png)

**Comment by copy-ninja1** [comment]
taken
