### ISSUE TITLE
Stop Promotion Screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#37]
Implement Stop Promotion Screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3524%3A48380

![STOP PROMOTION](https://user-images.githubusercontent.com/31111116/192760907-093ea056-c2fd-492d-8ee8-4efa06edb200.png)

**Comment by copy-ninja1** [comment]
taken
