### ISSUE TITLE
Restart Promotion screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#38]
Implement Restart Promotion screen 

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3524%3A48539

![RESTART PROMOTION](https://user-images.githubusercontent.com/31111116/192761314-27f1929f-2b43-4a42-b620-2a5d23e0dfda.png)

**Comment by copy-ninja1** [comment]
Am working on this

**Comment by copy-ninja1** [comment]
taken
