### ISSUE TITLE
Preview Job Screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#39]
Implement Preview Job Screen 

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=1968%3A15773

![Preview Job-1](https://user-images.githubusercontent.com/31111116/192761927-56362bd0-eda9-48f2-9ca5-6c7d88488ad3.png)
![Preview Job](https://user-images.githubusercontent.com/31111116/192761934-1027cba8-1c97-4ba1-8947-c6bfcaff8c2c.png)

**Comment by copy-ninja1** [comment]
taken
