### ISSUE TITLE
View Applicant Page Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#40]
Implement View Applicant Page 

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3524%3A48862

![VIEW APPLICANTS PAGE](https://user-images.githubusercontent.com/31111116/192762770-e82fab0e-8b8b-4b24-ab92-be3a3513cfba.png)

**Comment by KenjxJJ** [comment]
Hello, 
Can I take this up?

**Comment by KenjxJJ** [comment]
And any backend API to test with? Or this follows a UI implementation only...

**Comment by KenjxJJ** [comment]
I request for the removal of two applicants' pages under same dashboard directory.

**Comment by mahilday** [comment]
that has been done now @KenjxJJ
