### ISSUE TITLE
Acceptance & Rejection Email Builder Screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#41]
Implement the acceptance & rejection email builder screen 

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3563%3A51065

![REJECTION EMAIL BUILDER](https://user-images.githubusercontent.com/31111116/192763451-ccdd9e88-cb47-4266-a50e-aeb402c17850.png)

**Comment by aslam48** [comment]
i will work on this page
