### ISSUE TITLE
Verify Email/After Verification Screen Implementation

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#52]
Implement the verify email screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=5363%3A56104

![sign up](https://user-images.githubusercontent.com/96685215/197032473-528dd261-13dc-45c4-b656-b1b84b1f5ff9.png)

![Go to Login](https://user-images.githubusercontent.com/96685215/197032512-3fc4e3a3-24ca-40fc-a44a-e61067aec9dc.png)

**Comment by shagariboy** [comment]
I will work on this issue.

**Comment by Sochima-Aristotle** [comment]
Hi @mahilday and @shagariboy  do you mind if I take this issue?

**Comment by shagariboy** [comment]
Hi, @mahilday sorry for the delayed response. I have worked on this issue and had my pull request merged and unaware of any further tasks.
