### ISSUE TITLE
Landing Screen Implementation

### ISSUE THREAD

**Issue by adugamayuba** [AfriSplash-Remotely/Afrisplash-Frontend#6]
Implement Landing Screen

https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=3422%3A49759

![Final version](https://user-images.githubusercontent.com/31111116/191484993-3ba19bfb-0983-4e86-9d57-0891e857f005.png)

**Comment by ericjay1452** [comment]
I will be opting in for this one..

**Comment by mahilday** [comment]
Currently working on this

**Comment by adugamayuba** [comment]
Okay awesome
