### ISSUE TITLE
Candidate Settings Screen Implementation

### ISSUE THREAD

**Issue by CodigoGod** [AfriSplash-Remotely/Afrisplash-Frontend#72]
https://www.figma.com/file/VxoknphZySezGNvfr63r42/Afrisplash-Final-UI?node-id=5867%3A73174&t=vIhGPuj1EogNx8X1-1

![SETTINGS ( LANGUAGE)](https://user-images.githubusercontent.com/96685215/206573713-d33ad7f2-6d07-4451-b93d-2578fffff619.png)
![SETTINGS ( NOTIFICATION)](https://user-images.githubusercontent.com/96685215/206573719-24ad1c07-ffa3-43b9-88cf-a1f94556775c.png)
![SETTINGS ( SECURITY)](https://user-images.githubusercontent.com/96685215/206573724-8485b058-253b-46df-b85c-4129b725d10a.png)
![SETTINGS(CANDIDATES)](https://user-images.githubusercontent.com/96685215/206573728-0f05e5bf-ec94-492b-af98-d8722171481d.png)

**Comment by Ilesanmi-Erioluwa-Victor** [comment]
I will be working on the candidate settings, The one i commented on before, has already been done..
